# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/oraclejdk8
    steps:
      - checkout
      - run: sh execute.sh
  #test:
   # docker:
      #- image: circleci/<language>:<version TAG>
    #steps:
     # - checkout
     # - run: <command>
